export const LINK = {
  SPLASH: '/',
  MAIN: '/main',
  LOGIN: '/login',
  SIGNUP: '/signup',
  SIGNUP_SUCCESS: '/signup-success',
  FINDPW: '/findpw',
  FIMDID: '/findid',
  MYPAGE: '/mypage',
  CHAT: '/chat',
  POST: '/post',
  POSTING_HELP: '/posting/help',
  POSTING_FREE: '/posting/free',
  POST_DETAIL: '/post/:id',
  POST_HELP: '/post/help',
  POST_FREE: '/post/free',
  SEARCH: '/search',
  ALERT: '/alert',
} as const;
