export const LINK = {
  SPLASH: '/',
  MAIN: '/main',
  LOGIN: '/login',
  SIGNUP: '/signup',
  SIGNUP_SUCCESS: '/signup-success',
  FINDPW: '/findpw',
  FIMDID: '/findid',
  MYPAGE: '/mypage',
  CHAT: '/chat',
  POST: '/post',
  POSTING_HELP: '/posting/help',
  POSTING_FREE: '/posting/free',
  POST_DETAIL: '/post/:id',
  POST_HELP: '/post/help',
  POST_FREE: '/post/free',
  POST_EDIT: '/post/edit/:id',
  SEARCH: '/search',
  ALERT: '/alert',
  ADMIN_DECLARE: '/admin/declare',
  ADMIN_DECLARE_POST: '/admin/declare/post/:postId',
  ADMIN_DECLARE_REPLY: '/admin/declare/reply/:replyId',
  ADMIN_ACCOUNT: '/admin/account',
  ADMIN_LOGOUT: '/admin/logout',
} as const;
