const { VITE_APP_DEFAULT_PROFILE_IMG, VITE_APP_API_BASE_URL } = import.meta.env;

export const URL = {
  DEFAULT_PROFILE_IMG: VITE_APP_DEFAULT_PROFILE_IMG,
  API_BASE_URL: VITE_APP_API_BASE_URL,
} as const;
